#! /usr/bin/env bash
# shellcheck disable=SC2164
set -ex

apk add --no-cache --virtual install-deps --no-cache \
  autoconf \
  automake \
  file \
  gcc \
  git \
  g++ \
  libtool \
  libusb \
  libzip-dev \
  make \
  musl-dev \
  python3-dev \
  readline-dev

apk add --no-cache --virtual run-deps --no-cache \
  curl-dev \
  libusb-dev

git clone --recursive --depth=1 https://github.com/libimobiledevice/libplist
cd libplist
./autogen.sh --without-cython
make
make install
cd ..

git clone --recursive --depth=1 https://github.com/tihmstar/libfragmentzip
cd libfragmentzip
./autogen.sh
make
make install
cd ..

git clone --recursive --depth=1 https://github.com/libimobiledevice/libirecovery
cd libirecovery
./autogen.sh
make
make install
cd ..

git clone --recursive --depth=1 https://github.com/tihmstar/tsschecker.git
cd tsschecker
patch < /patches/libfragmentzip.patch
./autogen.sh
make
make install

apk del --virtual install-deps
